/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javafx.scene.paint.Color;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import model.Car;
import model.CarList;

/**
 *
 * @author dellpc
 */
public class CreateJPanel extends javax.swing.JPanel {

    CarList carList;
    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel(CarList carList) {
        initComponents();
        this.carList = carList;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblSeats = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblModelNumber = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        lblManufacturer = new javax.swing.JLabel();
        lblIsUseble = new javax.swing.JLabel();
        lblIsUpdated = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtBrand = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        txtSN = new javax.swing.JTextField();
        txtMN = new javax.swing.JTextField();
        txtManu = new javax.swing.JTextField();
        checkBoxIsUseble = new javax.swing.JCheckBox();
        checkBoxIsOutdated = new javax.swing.JCheckBox();
        txtCity = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(218, 244, 252));

        lblTitle.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 153, 204));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create");

        lblBrand.setFont(new java.awt.Font("微软雅黑", 2, 18)); // NOI18N
        lblBrand.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBrand.setText("Brand:");

        lblSeats.setFont(new java.awt.Font("微软雅黑", 2, 18)); // NOI18N
        lblSeats.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSeats.setText("Seats:");

        lblYear.setFont(new java.awt.Font("微软雅黑", 2, 18)); // NOI18N
        lblYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYear.setText("BuildYear:");

        lblModelNumber.setFont(new java.awt.Font("微软雅黑", 2, 18)); // NOI18N
        lblModelNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModelNumber.setText("ModelNumber:");

        lblSerialNumber.setFont(new java.awt.Font("微软雅黑", 2, 18)); // NOI18N
        lblSerialNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSerialNumber.setText("SerialNumber:");

        lblManufacturer.setFont(new java.awt.Font("微软雅黑", 2, 18)); // NOI18N
        lblManufacturer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblManufacturer.setText("Manufacturer:");

        lblIsUseble.setFont(new java.awt.Font("微软雅黑", 2, 18)); // NOI18N
        lblIsUseble.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIsUseble.setText("IsUseble:");

        lblIsUpdated.setFont(new java.awt.Font("微软雅黑", 2, 18)); // NOI18N
        lblIsUpdated.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIsUpdated.setText("IsOutdated:");

        btnSave.setBackground(new java.awt.Color(153, 204, 255));
        btnSave.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMNActionPerformed(evt);
            }
        });

        checkBoxIsUseble.setText("(If useble, choose it)");
        checkBoxIsUseble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxIsUsebleActionPerformed(evt);
            }
        });

        checkBoxIsOutdated.setText("(If outdated, choose it)");

        lblCity.setFont(new java.awt.Font("微软雅黑", 2, 18)); // NOI18N
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity.setText("City:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/main.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIsUseble, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIsUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkBoxIsUseble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkBoxIsOutdated, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCity))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblSerialNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblModelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblManufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtBrand)
                                .addComponent(txtYear)
                                .addComponent(txtSeats)
                                .addComponent(txtSN)
                                .addComponent(txtMN)
                                .addComponent(txtManu, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTitle)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, Short.MAX_VALUE)
                        .addGap(660, 660, 660))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBrand)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYear)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSeats)
                            .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSerialNumber)
                            .addComponent(txtSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModelNumber)
                            .addComponent(txtMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManufacturer)
                            .addComponent(txtManu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCity)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIsUseble)
                            .addComponent(checkBoxIsUseble))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIsUpdated)
                            .addComponent(checkBoxIsOutdated))
                        .addGap(7, 7, 7)
                        .addComponent(btnSave)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMNActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String brand = txtBrand.getText();
        String buildDate = txtYear.getText();
        
        int seats = 0;
        String serialNumber = txtSN.getText();
        boolean isUseble = checkBoxIsUseble.isSelected();
        String modelNumber = txtMN.getText();
        String city = txtCity.getText();
        boolean isOutdated = checkBoxIsOutdated.isSelected();
        String manufacturer = txtManu.getText();
        
        Car car = carList.addCar();
        
        boolean key = false;
        if(!txtBrand.getText().equals("")){
            car.setBrand(brand);
           key = true;
        }else{
            JOptionPane.showMessageDialog(new JDialog(),"Brand should not be null!");
        }
        
        boolean result = false;
        if(buildDate != null){
            String eL = "^((\\d{2}(([02468][048])|([13579][26]))[\\-\\/\\s]?((((0?[13578])|(1[02]))[\\-\\/\\s]?((0?[1-9])|([1-2][0-9])|(3[01])))|(((0?[469])|(11))[\\-\\/\\s]?((0?[1-9])|([1-2][0-9])|(30)))|(0?2[\\-\\/\\s]?((0?[1-9])|([1-2][0-9])))))|(\\d{2}(([02468][1235679])|([13579][01345789]))[\\-\\/\\s]?((((0?[13578])|(1[02]))[\\-\\/\\s]?((0?[1-9])|([1-2][0-9])|(3[01])))|(((0?[469])|(11))[\\-\\/\\s]?((0?[1-9])|([1-2][0-9])|(30)))|(0?2[\\-\\/\\s]?((0?[1-9])|(1[0-9])|(2[0-8]))))))"; 
            Pattern p = Pattern.compile(eL);
            Matcher m = p.matcher(buildDate);
            result = m.matches();
            if(result){
                car.setBuildDate(buildDate);
                
            }else{
                JOptionPane.showMessageDialog(new JDialog(),"Please input the correct BuildDate like YYYY-MM-DD!");
            }
        }else{
            JOptionPane.showMessageDialog(new JDialog(),"BuildDate should not be null!");
        }
        
        boolean key2 = false;
        if(!city.equals("")){
            car.setCity(city);
            key2 = true;
        }else{
            JOptionPane.showMessageDialog(new JDialog(),"Located City should not be null!");
        }
        
        car.setIsOutdated(isOutdated);
        car.setIsUseble(isUseble);
        
        boolean key3 = false;
        if(!manufacturer.equals("")){
            car.setManufacturer(manufacturer);
            key3 = true;
        }else{
            JOptionPane.showMessageDialog(new JDialog(),"Manufacturer should not be null!");
        }
        
        boolean key4 = false;
        if(!modelNumber.equals("")){
            car.setModelNumber(modelNumber);
            key4 = true;
        }else{
            JOptionPane.showMessageDialog(new JDialog(),"ModelNumber should not be null!");
        }
        
       
        Pattern pattern = Pattern.compile("^-?[0-9]+");
        Matcher isNum = pattern.matcher(txtSeats.getText());
        boolean key5 = false;
        if(isNum.matches()){
            seats = Integer.parseInt(txtSeats.getText());
            if(seats <= 0 || seats > 61){           
                JOptionPane.showMessageDialog(new JDialog(),"Please input the correct number of seats!");
            }else{
                car.setSeats(seats);
                key5 = true;
            }
        }else{
            JOptionPane.showMessageDialog(new JDialog(),"Number of seats should not be null!");
        }
        
        
        
        String regex ="(?i)^(?!([a-z]*|\\d*)$)[a-z\\d]+$";  
        boolean ju = false;
        if(serialNumber.length() == 17 && serialNumber.matches(regex) && carList.isOnlySN(serialNumber)){
            car.setSerialNumber(serialNumber);
            carList.setSerialList(carList.addSN(serialNumber));
            ju = true;
        }else{
            JOptionPane.showMessageDialog(new JDialog(),"Please input the correct SerialNumber or the SreialNumber already exists!");
        }
        
        
        if(key && key2 && key3 && key4 && ju && result && serialNumber.matches(regex) && key5){
            JOptionPane.showMessageDialog(this, "New Car added !");
        }else{
            carList.deleteCar(car);
            JOptionPane.showMessageDialog(new JDialog(),"Failed to create a new car! Try it again!");
        }
        
        
        txtBrand.setText("");
        txtCity.setText("");
        txtMN.setText("");
        txtManu.setText("");
        txtSN.setText("");
        txtSeats.setText("");
        txtYear.setText("");
        checkBoxIsUseble.setSelected(false);
        checkBoxIsOutdated.setSelected(false);
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void checkBoxIsUsebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxIsUsebleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxIsUsebleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox checkBoxIsOutdated;
    private javax.swing.JCheckBox checkBoxIsUseble;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblIsUpdated;
    private javax.swing.JLabel lblIsUseble;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtMN;
    private javax.swing.JTextField txtManu;
    private javax.swing.JTextField txtSN;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
