/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.HashSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Person;

/**
 *
 * @author dellpc
 */
public class CreateJPanel extends javax.swing.JPanel {

    Person person;
    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel(Person person) {
        initComponents();
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textAccount = new javax.swing.JTextField();
        labCertificateNumber = new javax.swing.JLabel();
        labVehicleIdentifiers = new javax.swing.JLabel();
        labVehicleSerialNumbers = new javax.swing.JLabel();
        labLicensePlate = new javax.swing.JLabel();
        labLinkedIn = new javax.swing.JLabel();
        textUnique = new javax.swing.JTextField();
        labDeviceId = new javax.swing.JLabel();
        textVId = new javax.swing.JTextField();
        labDeviceSerialNumbers = new javax.swing.JLabel();
        textVSN = new javax.swing.JTextField();
        labInternetAdd = new javax.swing.JLabel();
        textLicense = new javax.swing.JTextField();
        textDeviceId = new javax.swing.JTextField();
        textDeviceSN = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        photoPanel = new javax.swing.JPanel();
        btnUploadPhoto = new javax.swing.JButton();
        labPhoto = new javax.swing.JLabel();
        labName = new javax.swing.JLabel();
        labGeographicData = new javax.swing.JLabel();
        labBirthDate = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        labUnique = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        textGeoData = new javax.swing.JTextField();
        labPhoneNumber = new javax.swing.JLabel();
        textBirth = new javax.swing.JTextField();
        labFaxNumber = new javax.swing.JLabel();
        textPhone = new javax.swing.JTextField();
        labEmail = new javax.swing.JLabel();
        textFAXNumber = new javax.swing.JTextField();
        labSSN = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        labMedicalNumber = new javax.swing.JLabel();
        textSSN = new javax.swing.JTextField();
        lanHealthNumber = new javax.swing.JLabel();
        textMedical = new javax.swing.JTextField();
        labAccount = new javax.swing.JLabel();
        textHealth = new javax.swing.JTextField();
        textCertificateNumber = new javax.swing.JTextField();
        textLinkedIn = new javax.swing.JTextField();
        textInternetPro = new javax.swing.JTextField();

        labCertificateNumber.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labCertificateNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labCertificateNumber.setText("CertificateNumber");

        labVehicleIdentifiers.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labVehicleIdentifiers.setText("VehicleIdentifiers");

        labVehicleSerialNumbers.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labVehicleSerialNumbers.setText("SerialNumbers");

        labLicensePlate.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labLicensePlate.setText("LicensePlate");

        labLinkedIn.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labLinkedIn.setText("LinkedIn");

        labDeviceId.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labDeviceId.setText("DeviceIdentifiers");

        labDeviceSerialNumbers.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labDeviceSerialNumbers.setText("SerialNumbers");

        labInternetAdd.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labInternetAdd.setText("InternetProtocolAddresses");

        btnSave.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUploadPhoto.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        btnUploadPhoto.setText("UploadPhoto");
        btnUploadPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadPhotoActionPerformed(evt);
            }
        });

        labPhoto.setText("UploadPhoto");

        javax.swing.GroupLayout photoPanelLayout = new javax.swing.GroupLayout(photoPanel);
        photoPanel.setLayout(photoPanelLayout);
        photoPanelLayout.setHorizontalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(photoPanelLayout.createSequentialGroup()
                .addGroup(photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(photoPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnUploadPhoto))
                    .addGroup(photoPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(labPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        photoPanelLayout.setVerticalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(photoPanelLayout.createSequentialGroup()
                .addComponent(labPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUploadPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        labName.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labName.setText("Name");

        labGeographicData.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labGeographicData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labGeographicData.setText("GeographicData");

        labBirthDate.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labBirthDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labBirthDate.setText("BirthDate");

        lbTitle.setFont(new java.awt.Font("微软雅黑", 3, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Personal Information Creation");

        labUnique.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labUnique.setText("NUID");

        labPhoneNumber.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labPhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labPhoneNumber.setText("PhoneNumber");

        labFaxNumber.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labFaxNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labFaxNumber.setText("FaxNumber");

        labEmail.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labEmail.setText("Email");

        labSSN.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labSSN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labSSN.setText("SocialSecurityNumber");

        labMedicalNumber.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labMedicalNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labMedicalNumber.setText("MedicalRecordNumber");

        lanHealthNumber.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        lanHealthNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lanHealthNumber.setText("HealthBeneficiaryNumber");

        labAccount.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labAccount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labAccount.setText("BankAccount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(photoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labGeographicData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labBirthDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labFaxNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFAXNumber)
                                    .addComponent(textBirth)
                                    .addComponent(textPhone)
                                    .addComponent(textGeoData)
                                    .addComponent(textName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labCertificateNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(labMedicalNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lanHealthNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labSSN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textCertificateNumber)
                                    .addComponent(textAccount)
                                    .addComponent(textHealth)
                                    .addComponent(textMedical)
                                    .addComponent(textSSN)
                                    .addComponent(textEmail)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labLinkedIn)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labVehicleIdentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(labDeviceId))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(textVId, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(textDeviceId, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(323, 323, 323)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(labDeviceSerialNumbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(labVehicleSerialNumbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textVSN, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(textDeviceSN))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labUnique, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textUnique))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(labInternetAdd)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textInternetPro))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(234, 234, 234)
                                                .addComponent(textLinkedIn)))
                                        .addGap(133, 133, 133)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(178, 178, 178))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labLicensePlate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textLicense)))))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labName)
                            .addComponent(labEmail)
                            .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labSSN)
                            .addComponent(textGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labGeographicData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textMedical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labMedicalNumber)
                            .addComponent(textBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labBirthDate))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lanHealthNumber)
                            .addComponent(textPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labPhoneNumber))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labAccount)
                            .addComponent(textAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFAXNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labFaxNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textCertificateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labCertificateNumber)))
                    .addComponent(photoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labVehicleIdentifiers)
                    .addComponent(labLicensePlate)
                    .addComponent(labDeviceSerialNumbers)
                    .addComponent(textVId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textVSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labDeviceId)
                        .addComponent(labVehicleSerialNumbers)
                        .addComponent(textDeviceSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textDeviceId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labLinkedIn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labInternetAdd)
                            .addComponent(textInternetPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnSave)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labUnique)
                    .addComponent(textUnique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        person.setName(textName.getText());
        person.setGeographicData(textGeoData.getText());
        
        String str = textBirth.getText();
        String eL= "^((\\d{2}(([02468][048])|([13579][26]))[\\-\\/\\s]?((((0?[13578])|(1[02]))[\\-\\/\\s]?((0?[1-9])|([1-2][0-9])|(3[01])))|(((0?[469])|(11))[\\-\\/\\s]?((0?[1-9])|([1-2][0-9])|(30)))|(0?2[\\-\\/\\s]?((0?[1-9])|([1-2][0-9])))))|(\\d{2}(([02468][1235679])|([13579][01345789]))[\\-\\/\\s]?((((0?[13578])|(1[02]))[\\-\\/\\s]?((0?[1-9])|([1-2][0-9])|(3[01])))|(((0?[469])|(11))[\\-\\/\\s]?((0?[1-9])|([1-2][0-9])|(30)))|(0?2[\\-\\/\\s]?((0?[1-9])|(1[0-9])|(2[0-8]))))))"; 
        Pattern p = Pattern.compile(eL);
        Matcher m = p.matcher(str);
        boolean result = m.matches();
        if(result){
            person.setBirthDate(textBirth.getText());
        }else{
            JOptionPane.showMessageDialog(new JDialog(),"Please input the correct BirthDate like YYYY-MM-DD!");
        }
        
        String fax = textFAXNumber.getText();
        if(fax.charAt(0) == '0' && fax.charAt(1) == '0' && fax.charAt(2) == '1' && fax.length() == 13){
            person.setFaxNumber(textFAXNumber.getText());
        }else{
            JOptionPane.showMessageDialog(new JDialog(),"Please input the correct Fax Number!");
        }
        
        String phone = textPhone.getText();
        if(phone.matches("[0-9]{1,}") && phone.length() == 10){
            person.setPhoneNumber(textPhone.getText());
        }else{
            JOptionPane.showMessageDialog(new JDialog(),"Please input the correct Phone Number!");
        }
        
        String email = textEmail.getText();
        boolean flagEmail = false;
        for(int i = 0; i<email.length();i++){
            if(email.charAt(i) == '@' && i != (email.length() - 1) && i != 0){
                flagEmail = true;
                break;
            }
        }
        if(flagEmail){
            person.setEmail(textEmail.getText());
        }else{
            JOptionPane.showMessageDialog(new JDialog(),"Please input the correct Email address!");
        } 
        
        String SSN = textSSN.getText();
        if(SSN.matches("[0-9]{1,}") && SSN.length() == 9){
            person.setSsn(textSSN.getText());
        }else{
             JOptionPane.showMessageDialog(new JDialog(),"Please input the correct SSN number!");
        }
        
        person.setMedicalNumber(textMedical.getText());
        person.setHealthNumber(textHealth.getText());
        
        String account = textAccount.getText();
        if(account.matches("[0-9]{1,}") && account.length() == 12){
            person.setBankAccount(textAccount.getText());
        }else{
            JOptionPane.showMessageDialog(new JDialog(),"Please input the correct Bank Account!");
        }
        
        person.setCertificateNumber(textCertificateNumber.getText());
        person.setVehicleIdentifier(textVId.getText());
        person.setVehileSerialNumber(textVSN.getText());
        person.setLicensePlate(textLicense.getText());
        person.setDeviceIdentifier(textDeviceId.getText());
        person.setDeviceSerialNumber(textDeviceSN.getText());
        person.setLinkedIn(textLinkedIn.getText());
        person.setInternetProtocol(textInternetPro.getText());
        
        String nuid = textUnique.getText();
        if(textUnique.getText() != null){
            if(nuid.matches("[0-9]{1,}") && nuid.length() == 9){
            person.setUniqueNumber(textUnique.getText());
        }else{
            JOptionPane.showMessageDialog(new JDialog(),"Please input the correct NUID!");
        }
        }
        
        
        JOptionPane.showMessageDialog(this, "Person Information Saved!");
        
       
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUploadPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPhotoActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(true);
	FileNameExtensionFilter filter = new FileNameExtensionFilter("jpg","png");
	chooser.setFileFilter(filter);
	int returnVal = chooser.showOpenDialog(btnUploadPhoto);
        if (returnVal == JFileChooser.APPROVE_OPTION) { 
            File[] arrfiles = chooser.getSelectedFiles();
            if (arrfiles == null || arrfiles.length == 0) {
                return;
            }	   
	File  ff = chooser.getSelectedFile();
	String fileName =ff.getName();
	String prefix=fileName.substring(fileName.lastIndexOf(".")+1);
	if(!(prefix.equals("jpg") || prefix.equals("png"))){
            JOptionPane.showMessageDialog(new JDialog(),":Please choose the .jpg or .png photos!");
            return;
        }
	FileInputStream input = null;
	FileOutputStream out = null;
	String path = "D:\\NetBeansProjects\\Assignment1\\src\\resources";
	try {
            for (File f : arrfiles) {
                File dir = new File(path);
		File[] fs = dir.listFiles();
		HashSet<String> set = new HashSet<String>();
		for (File file : fs) {
                    set.add(file.getName());
                }
                if (set.contains(f.getName())) {
                    JOptionPane.showMessageDialog(new JDialog(),f.getName() + ":The photo's name already exits！");
                    return;
                }
                
                String absolutePath = chooser.getSelectedFile().getAbsolutePath();
		ImageIcon imageIcon = new ImageIcon(absolutePath);
                person.setPhoto(imageIcon);
                labPhoto.setIcon(imageIcon);
		labPhoto.getIcon();
		input = new FileInputStream(f);
		byte[] buffer = new byte[1024];
		File des = new File(path, f.getName());
                
                out = new FileOutputStream(des);
		int len = 0;
		while (-1 != (len = input.read(buffer))) {
                    out.write(buffer, 0, len);
                }
                out.close();
		input.close();
		}
		JOptionPane.showMessageDialog(null, "Uploaded the photo successfully！", "Message",JOptionPane.INFORMATION_MESSAGE);
        } catch (FileNotFoundException e1) {
            JOptionPane.showMessageDialog(null, "Failed to upload the photo！", "Message",JOptionPane.ERROR_MESSAGE);
            e1.printStackTrace();
        } catch (IOException e1) {
            JOptionPane.showMessageDialog(null, "Failed to upload the photo！", "Message",JOptionPane.ERROR_MESSAGE);
            e1.printStackTrace();
        }
        }
		 

    }//GEN-LAST:event_btnUploadPhotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUploadPhoto;
    private javax.swing.JLabel labAccount;
    private javax.swing.JLabel labBirthDate;
    private javax.swing.JLabel labCertificateNumber;
    private javax.swing.JLabel labDeviceId;
    private javax.swing.JLabel labDeviceSerialNumbers;
    private javax.swing.JLabel labEmail;
    private javax.swing.JLabel labFaxNumber;
    private javax.swing.JLabel labGeographicData;
    private javax.swing.JLabel labInternetAdd;
    private javax.swing.JLabel labLicensePlate;
    private javax.swing.JLabel labLinkedIn;
    private javax.swing.JLabel labMedicalNumber;
    private javax.swing.JLabel labName;
    private javax.swing.JLabel labPhoneNumber;
    private javax.swing.JLabel labPhoto;
    private javax.swing.JLabel labSSN;
    private javax.swing.JLabel labUnique;
    private javax.swing.JLabel labVehicleIdentifiers;
    private javax.swing.JLabel labVehicleSerialNumbers;
    private javax.swing.JLabel lanHealthNumber;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel photoPanel;
    private javax.swing.JTextField textAccount;
    private javax.swing.JTextField textBirth;
    private javax.swing.JTextField textCertificateNumber;
    private javax.swing.JTextField textDeviceId;
    private javax.swing.JTextField textDeviceSN;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textFAXNumber;
    private javax.swing.JTextField textGeoData;
    private javax.swing.JTextField textHealth;
    private javax.swing.JTextField textInternetPro;
    private javax.swing.JTextField textLicense;
    private javax.swing.JTextField textLinkedIn;
    private javax.swing.JTextField textMedical;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textPhone;
    private javax.swing.JTextField textSSN;
    private javax.swing.JTextField textUnique;
    private javax.swing.JTextField textVId;
    private javax.swing.JTextField textVSN;
    // End of variables declaration//GEN-END:variables
}
