/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import model.Person;

/**
 *
 * @author dellpc
 */
public class ViewJPanel extends javax.swing.JPanel {
    
    Person person;
    

    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel(Person person) {
        initComponents();
        this.person = person;
        displayPerson();
    }
    
    private void displayPerson() {
        
        textName.setText(person.getName());
        textGeoData.setText(person.getGeographicData());
        
        if(person.getBirthDate() != null){
            textBirth.setText(person.getBirthDate());
        }else{
            textBirth.setText("");
        }
        textFAXNumber.setText(person.getFaxNumber());
        textPhone.setText(person.getPhoneNumber());
        
        if(person.getEmail() != null){
            textEmail.setText(person.getEmail());
        }else{
            textEmail.setText("");
        }
        
        if(person.getSsn() != null){
            textSSN.setText(person.getSsn());
        }else{
            textSSN.setText("");
        }
        if(person.getMedicalNumber() != null){
            textMedical.setText(person.getMedicalNumber());
        }else{
            textMedical.setText("");
        }
        
        if(person.getHealthNumber() != null){
            textHealth.setText(person.getHealthNumber());
        }else{
            textHealth.setText("");
        }
        
        
        if(person.getBankAccount() != null){
            textAccount.setText(person.getBankAccount());
        }else{
            textAccount.setText("");
        }
        textCertificateNumber.setText(person.getCertificateNumber());
        textVId.setText(person.getVehicleIdentifier());
        textVSN.setText(person.getVehileSerialNumber());
        textLicense.setText(person.getLicensePlate());
        textDeviceId.setText(person.getDeviceIdentifier());
        textDeviceSN.setText(person.getDeviceSerialNumber());
        textLinkedIn.setText(person.getLinkedIn());
        textInternetPro.setText(person.getInternetProtocol());
        textUnique.setText(person.getUniqueNumber());
        //if(person.getUniqueNumber() != null)
        
        if(person.getPhoto() != null){
            ImageIcon icon = person.getPhoto();
            icon.setImage(icon.getImage().getScaledInstance(220,300,Image.SCALE_DEFAULT));
            labShowPhoto.setIcon(icon);
        }else{
            labShowPhoto.setIcon(null);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textEmail = new javax.swing.JTextField();
        labMedicalNumber = new javax.swing.JLabel();
        textSSN = new javax.swing.JTextField();
        lanHealthNumber = new javax.swing.JLabel();
        textMedical = new javax.swing.JTextField();
        labAccount = new javax.swing.JLabel();
        photoPanel = new javax.swing.JPanel();
        labShowPhoto = new javax.swing.JLabel();
        textHealth = new javax.swing.JTextField();
        labName = new javax.swing.JLabel();
        textCertificateNumber = new javax.swing.JTextField();
        labGeographicData = new javax.swing.JLabel();
        textLinkedIn = new javax.swing.JTextField();
        labBirthDate = new javax.swing.JLabel();
        textInternetPro = new javax.swing.JTextField();
        lbTitle = new javax.swing.JLabel();
        textAccount = new javax.swing.JTextField();
        labUnique = new javax.swing.JLabel();
        labCertificateNumber = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        textGeoData = new javax.swing.JTextField();
        labPhoneNumber = new javax.swing.JLabel();
        labLinkedIn = new javax.swing.JLabel();
        textBirth = new javax.swing.JTextField();
        textUnique = new javax.swing.JTextField();
        labFaxNumber = new javax.swing.JLabel();
        textPhone = new javax.swing.JTextField();
        labEmail = new javax.swing.JLabel();
        textFAXNumber = new javax.swing.JTextField();
        labSSN = new javax.swing.JLabel();
        labInternetAdd = new javax.swing.JLabel();
        labVehicleSerialNumbers = new javax.swing.JLabel();
        labLicensePlate = new javax.swing.JLabel();
        labDeviceId = new javax.swing.JLabel();
        textVId = new javax.swing.JTextField();
        labDeviceSerialNumbers = new javax.swing.JLabel();
        textVSN = new javax.swing.JTextField();
        textLicense = new javax.swing.JTextField();
        textDeviceId = new javax.swing.JTextField();
        textDeviceSN = new javax.swing.JTextField();
        labVehicleIdentifiers = new javax.swing.JLabel();

        labMedicalNumber.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labMedicalNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labMedicalNumber.setText("MedicalRecordNumber");

        lanHealthNumber.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        lanHealthNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lanHealthNumber.setText("HealthBeneficiaryNumber");

        labAccount.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labAccount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labAccount.setText("BankAccount");

        javax.swing.GroupLayout photoPanelLayout = new javax.swing.GroupLayout(photoPanel);
        photoPanel.setLayout(photoPanelLayout);
        photoPanelLayout.setHorizontalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(photoPanelLayout.createSequentialGroup()
                .addComponent(labShowPhoto)
                .addGap(0, 104, Short.MAX_VALUE))
        );
        photoPanelLayout.setVerticalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(photoPanelLayout.createSequentialGroup()
                .addComponent(labShowPhoto)
                .addGap(0, 188, Short.MAX_VALUE))
        );

        labName.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labName.setText("Name");

        labGeographicData.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labGeographicData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labGeographicData.setText("GeographicData");

        labBirthDate.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labBirthDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labBirthDate.setText("BirthDate");

        lbTitle.setFont(new java.awt.Font("微软雅黑", 3, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Personal Information Veiw");

        labUnique.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labUnique.setText("NUID");

        labCertificateNumber.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labCertificateNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labCertificateNumber.setText("CertificateNumber");

        labPhoneNumber.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labPhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labPhoneNumber.setText("PhoneNumber");

        labLinkedIn.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labLinkedIn.setText("LinkedIn");

        labFaxNumber.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labFaxNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labFaxNumber.setText("FaxNumber");

        labEmail.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labEmail.setText("Email");

        labSSN.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labSSN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labSSN.setText("SocialSecurityNumber");

        labInternetAdd.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labInternetAdd.setText("InternetProtocolAddresses");

        labVehicleSerialNumbers.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labVehicleSerialNumbers.setText("SerialNumbers");

        labLicensePlate.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labLicensePlate.setText("LicensePlate");

        labDeviceId.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labDeviceId.setText("DeviceIdentifiers");

        labDeviceSerialNumbers.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labDeviceSerialNumbers.setText("SerialNumbers");

        labVehicleIdentifiers.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        labVehicleIdentifiers.setText("VehicleIdentifiers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(photoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labGeographicData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labBirthDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labFaxNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFAXNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(textBirth)
                            .addComponent(textPhone)
                            .addComponent(textGeoData)
                            .addComponent(textName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labCertificateNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labMedicalNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lanHealthNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labSSN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCertificateNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(textAccount)
                            .addComponent(textHealth)
                            .addComponent(textMedical)
                            .addComponent(textSSN)
                            .addComponent(textEmail)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labUnique, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textUnique))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labInternetAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textInternetPro))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addComponent(textLinkedIn)))
                        .addGap(428, 428, 428))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labLinkedIn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labVehicleIdentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labDeviceId))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textVId, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(textDeviceId, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(323, 323, 323)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labDeviceSerialNumbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labVehicleSerialNumbers))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textVSN)
                            .addComponent(textDeviceSN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labLicensePlate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textLicense, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labName)
                            .addComponent(labEmail)
                            .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labSSN)
                            .addComponent(textGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labGeographicData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textMedical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labMedicalNumber)
                            .addComponent(textBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labBirthDate))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lanHealthNumber)
                            .addComponent(textPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labPhoneNumber))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labAccount)
                            .addComponent(textAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFAXNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labFaxNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textCertificateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labCertificateNumber)))
                    .addComponent(photoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labVehicleIdentifiers)
                    .addComponent(labLicensePlate)
                    .addComponent(labDeviceSerialNumbers)
                    .addComponent(textVId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textVSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labDeviceId)
                        .addComponent(labVehicleSerialNumbers)
                        .addComponent(textDeviceSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textDeviceId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labLinkedIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labInternetAdd)
                    .addComponent(textInternetPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labUnique)
                    .addComponent(textUnique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labAccount;
    private javax.swing.JLabel labBirthDate;
    private javax.swing.JLabel labCertificateNumber;
    private javax.swing.JLabel labDeviceId;
    private javax.swing.JLabel labDeviceSerialNumbers;
    private javax.swing.JLabel labEmail;
    private javax.swing.JLabel labFaxNumber;
    private javax.swing.JLabel labGeographicData;
    private javax.swing.JLabel labInternetAdd;
    private javax.swing.JLabel labLicensePlate;
    private javax.swing.JLabel labLinkedIn;
    private javax.swing.JLabel labMedicalNumber;
    private javax.swing.JLabel labName;
    private javax.swing.JLabel labPhoneNumber;
    private javax.swing.JLabel labSSN;
    private javax.swing.JLabel labShowPhoto;
    private javax.swing.JLabel labUnique;
    private javax.swing.JLabel labVehicleIdentifiers;
    private javax.swing.JLabel labVehicleSerialNumbers;
    private javax.swing.JLabel lanHealthNumber;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel photoPanel;
    private javax.swing.JTextField textAccount;
    private javax.swing.JTextField textBirth;
    private javax.swing.JTextField textCertificateNumber;
    private javax.swing.JTextField textDeviceId;
    private javax.swing.JTextField textDeviceSN;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textFAXNumber;
    private javax.swing.JTextField textGeoData;
    private javax.swing.JTextField textHealth;
    private javax.swing.JTextField textInternetPro;
    private javax.swing.JTextField textLicense;
    private javax.swing.JTextField textLinkedIn;
    private javax.swing.JTextField textMedical;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textPhone;
    private javax.swing.JTextField textSSN;
    private javax.swing.JTextField textUnique;
    private javax.swing.JTextField textVId;
    private javax.swing.JTextField textVSN;
    // End of variables declaration//GEN-END:variables

    
}
